### ISSUE TITLE
Missing status "failed" when the volumes are not create

### ISSUE THREAD

**Issue by nirekin** [lagoon-platform/aws-provider#11]
I'm passing those wrong parameters to create  volumes on an xlarge machine:

```yaml
connectionConfig:
  #...
  provider: aws
environment:
  #...
instances: 3
labels: {}
params:
  ami_id: ami-027583e616ca104df
  instance_type: m5.4xlarge
  #...
volumes:
- path: /var/lib/docker
  params:
    delete_on_termination: true
    device_name: xvdg
    tags:
      Type: Docker
    volume_size: 100
    volume_type: gp2
- path: /users
  params:
    delete_on_termination: true
    device_name: xvdf
    volume_size: 200
    volume_type: gp2
```

The volumes are not created and the playbook returns without failure
[container.log](https://github.com/ekara-platform/aws-provider/files/2624921/container.log)
[params.yaml.txt](https://github.com/ekara-platform/aws-provider/files/2624964/params.yaml.txt)
