### ISSUE TITLE
No inherit environment variables from the provider to the descriptor

### ISSUE THREAD

**Issue by nirekin** [lagoon-platform/aws-provider#15]
When defined into the components environment variables are not inherited by the provider at runtime.

Used `ekara-platform/aws-provider/ekara.yaml`

```yaml
providers:
  aws:
    env:
      AWS_REGION: {{ .aws_region }}
      AWS_ACCESS_KEY_ID: {{ .aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: {{ .aws_access_key }}
```

This will result in the following error trying to create an environment:

```
Ekara INSTALLER LOG:2019/04/01 14:07:33.444536 TASK [Create a new ec2 key pair] ***********************************************
Ekara INSTALLER LOG:2019/04/01 14:07:34.887295 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: Authorization header or parameters are not formatted correctly.
Ekara INSTALLER LOG:2019/04/01 14:07:34.888966 fatal: [localhost]: FAILED! => {"boto3_version": "1.9.64", "botocore_version": "1.12.64", "changed": false, "error": {"code": "AuthFailure", "message": "Authorization header or parameters are not formatted correctly."}, "msg": "error finding keypair: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: Authorization header or parameters are not formatted correctly.", "response_metadata": {"http_headers": {"date": "Mon, 01 Apr 2019 14:07:34 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 401, "request_id": "d98f47be-0798-4414-9cb2-3245110995da", "retry_attempts": 0}}
```
