### ISSUE TITLE
Support EFS distributed filesystems

### ISSUE THREAD

**Issue by adrienlauer** [lagoon-platform/aws-provider#21]
EFS shared filesystems should be supported with the following parameters:

```yaml
volumes:
  efs:
    ...
  fs:
    mount_path: ...
```
